# _____ _    _ _____ _    _
#/  __ \ |  | /  ___| |  (_)
#| /  \/ |  | \ `--.| | ___ _ __  ___
#| |   | |/\| |`--. \ |/ / | '_ \/ __|
#| \__/\  /\  /\__/ /   <| | | | \__ \
# \____/\/  \/\____/|_|\_\_|_| |_|___/

items:
  clearSkinItem:
    material: "CLAY_BALL"
    name: "&#d16c13Skin clear"
    lore:
      - ""
      - "&8▪ &fDrag this item on skin"
      - "  &fto clear it"