# _____ _    _ _____ _    _
#/  __ \ |  | /  ___| |  (_)
#| /  \/ |  | \ `--.| | ___ _ __  ___
#| |   | |/\| |`--. \ |/ / | '_ \/ __|
#| \__/\  /\  /\__/ /   <| | | | \__ \
# \____/\/  \/\____/|_|\_\_|_| |_|___/


# All messages can be configured in messages.json file.
# Config supports only color codes, locale file supports only MiniMessage format.
# Multiple color support will be in future versions.

check-for-updates: true

items:
  clearSkinItem:
    material: "CLAY_BALL"
    name: "&#d16c13Skin clear"
    lore:
      - ""
      - "&8▪ &fDrag this item on skin"
      - "  &fto clear it"

menu:
  nextButton:
    displayName: "&aNext Page"
    customModelData: 10006 # Set this to -1 for disabling
    material: PAPER
  backButton:
    displayName : "&aPrevious Page"
    customModelData: 10005
    material: PAPER

# Prevents skin from using.
# Needs to restart server.
restrictions:
  prevent-skin-from-using: true
  prevent-skin-from-enchanting: true
  prevent-skin-from-anvil: true
  prevent-damage-from-skin: true