name: CWSkins
version: '${project.version}'
main: me.skellf.cwskins.CWSkins
api-version: '1.16'
author: skellf
description: Plugin for simple skin support.
commands:
  cwskins:
    usage: /cwskins <reload|menu|give|clear|create>
    description: Main command of plugin
    aliases: cws
permissions:
  cwskins.*:
    description: Grants permission for all commands
    default: op
    children:
      cwskins.clearskin: true
      cwskins.createskin: true
      cwskins.giveskin: true
      cwskins.reload: true
      cwskins.menu: true
      cwskins.removeskin: true
  cwskins.clearskin:
    description: Permission for giving clear skin item
  cwskins.createskin:
    description: Permission for creating skin
  cwskins.giveskin:
    description: Permission for giving skin
  cwskins.reload:
    description: Permission for plugin reload
  cwskins.menu:
    description: Permission for open skins menu
  cwskins.removeskin:
    description: Permission for removing skin