name: CWSkins
version: '${project.version}'
main: me.skellf.cwskins.CWSkins
api-version: '1.20'
author: skellf
description: Plugin for simple skin support.
commands:
  clearskin:
    usage: /clearskin
    description: Command for giving clear skin item
  createskin:
    usage: /createskin <skin name>
    description: Command for creating skin
  giveskin:
    usage: /giveskin <player> <skin>
    description: Command for receiving skins
  cwskinsreload:
    usage: /cwskins reload
    description: Reloads the plugin
permissions:
  cwskins.clearskin:
    default: op
    description: Permission for command clearskin
  cwskins.createskin:
    default: op
    description: Permission for command createskin
  cwskins.giveskin:
    default: op
    description: Permission for command giveskin
  cwskins.reload:
    default: op
    description: Permission for plugin reload