name: CWSkins
version: '${project.version}'
main: me.skellf.cwskins.CWSkins
api-version: '1.20'
author: skellf
description: Plugin for simple skin support.
commands:
  cwskins:
    usage: /cwskins <reload|menu|give|clear|create>
    description: Main command of plugin
    aliases: cws
permissions:
  cwskins.clearskin:
    default: op
    description: Permission for giving clear skin item
  cwskins.createskin:
    default: op
    description: Permission for creating skin
  cwskins.giveskin:
    default: op
    description: Permission for giving skin
  cwskins.reload:
    default: op
    description: Permission for plugin reload
  cwskins.menu:
    default: op
    description: Permission for open skins menu
  cwskins.removeskin:
    default: op
    description: Permission for removing skin