name: CWSkins
version: '${project.version}'
main: me.skellf.cwskins.CWSkins
api-version: '1.20'
author: skellf
description: Плагин на скины для сервера CrazyWorld.
commands:
  clearskin:
    usage: /clearskin
    description: Комманда для применения скина
  createskin:
    usage: /createskin <название скина>
    description: Комманда для создания скина
  giveskin:
    usage: /giveskin <игрок> <скин>
    description: Комманда для получения скина
permissions:
  cwskins.clearskin:
    default: op
    description: Разрещение на комманду clearskin
  cwskins.createskin:
    default: op
    description: Разрешение на комманду createskin
  cwskins.giveskin:
    default: op
    description: Разрешение на комманду giveskin